# This is a generated file. Not intended for manual editing.
services:
  hr.leavemanagement.api:
    build:
      context: "/Users/aberikashvili/Projects/Personal/HR.LeaveManagement.Clean"
      dockerfile: "HR.LeaveManagement.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57405"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "hr.leavemanagement.api:dev"
    ports:
    - "127.0.0.1:57005:57000"
    - "127.0.0.1:57205:57200"
    - "127.0.0.1:57405:57405"
    volumes:
    - "/Users/aberikashvili/Projects/Personal/HR.LeaveManagement.Clean/HR.LeaveManagement.Api:/app:rw"
    - "/Users/aberikashvili/Projects/Personal/HR.LeaveManagement.Clean:/src:rw"
    - "/Users/aberikashvili/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/aberikashvili/.local/share/JetBrains/RiderRemoteDebugger/2025.2.4/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/aberikashvili/Library/Logs/JetBrains/Rider2025.2/DebuggerWorker/JetBrains.Debugger.Worker.2025_11_05_16_47_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
